/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.TextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.sf.clipsrules.jni.*;

/**
 *
 * @author Mostafa
 */
public class JFrameInterface extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInterface
     */
    
    Environment clips;
            
    public JFrameInterface() {
        clips = new Environment();
        clips.load("flower.clp");
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        startButton = new javax.swing.JButton();
        showFactsButton = new javax.swing.JButton();
        SizeSlider = new javax.swing.JSlider();
        ColorComboBox = new javax.swing.JComboBox<>();
        SeasonComboBox = new javax.swing.JComboBox<>();
        LifeCycleComboBox = new javax.swing.JComboBox<>();
        RootComboBox = new javax.swing.JComboBox<>();
        SoilComboBox = new javax.swing.JComboBox<>();
        PerfumeComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SizeSliderTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startButton.setText("start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        showFactsButton.setText("Show Facts");
        showFactsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFactsButtonActionPerformed(evt);
            }
        });

        SizeSlider.setValue(10);
        SizeSlider.setMinimum(10);
        SizeSlider.setMaximum(300);
        SizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SizeSliderStateChanged(evt);
            }
        });

        ColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Red", "Blue", "Yellow", "White", "Pink", "Purple", "Pinkish-Red" }));
        ColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorComboBoxActionPerformed(evt);
            }
        });

        SeasonComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Summer", "Spring", "Autumn", "Winter" }));

        LifeCycleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "One", "More" }));

        RootComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Bulb", "Root" }));

        SoilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Acidic", "Loose", "Fertile", "Rich", "Well-Drained" }));

        PerfumeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "True", "False" }));

        jLabel1.setText("Size");

        jLabel2.setText("Life Cycle");

        jLabel3.setText("Color");

        jLabel4.setText("Season");

        jLabel5.setText("Root");

        jLabel6.setText("Soil");

        jLabel7.setText("Perfume");

        SizeSliderTextField.setText("10");
        SizeSliderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeSliderTextFieldActionPerformed(evt);
            }
        });
        SizeSliderTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SizeSliderTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SizeSliderTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showFactsButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ColorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SeasonComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LifeCycleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RootComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SoilComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PerfumeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 206, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SizeSliderTextField)
                    .addComponent(SizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LifeCycleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RootComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SoilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerfumeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showFactsButton)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
            // TODO add your handling code here:
            clips.reset();
            
            String Size = Integer.toString(SizeSlider.getValue());
            clips.eval("(assert (Size (PlantSize " + Size + ")))");
            
            String LifeCycle = LifeCycleComboBox.getSelectedItem().toString().toLowerCase();
            if(!LifeCycle.equals(" "))
                clips.eval("(assert (LifeCycle (PLifeCycle " + LifeCycle + ")))");
                
            String Color = ColorComboBox.getSelectedItem().toString().toLowerCase();
            if(Color.length()>2)
                clips.eval("(assert (Color (PlantColor " + Color + ")))");
            
            String Season = SeasonComboBox.getSelectedItem().toString().toLowerCase();
            if(!Season.equals(" "))
                clips.eval("(assert (Season (PlantSeason " + Season + ")))");
            
            String Root = RootComboBox.getSelectedItem().toString().toLowerCase();
            if(!Root.equals(" "))
                clips.eval("(assert (Root (PlantRoot " + Root + ")))");
            
            String Soil = SoilComboBox.getSelectedItem().toString().toLowerCase();
            if(Soil.length()>2)
                clips.eval("(assert (Soil (PlantSoil " + Soil + ")))");
            
            String Perfume = PerfumeComboBox.getSelectedItem().toString().toLowerCase();
            if(Perfume.length()>2)
                clips.eval("(assert (Perfume (PlantPerfume " + Perfume + ")))");
            
            
            clips.run();
            
    }//GEN-LAST:event_startButtonActionPerformed

    private void showFactsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showFactsButtonActionPerformed
        
        clips.eval("(facts)");
        
    }//GEN-LAST:event_showFactsButtonActionPerformed

    private void ColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorComboBoxActionPerformed

    private void SizeSliderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeSliderTextFieldActionPerformed
        String sliderText = SizeSliderTextField.getText();
        try {
        Integer.parseInt(sliderText);
        int x = Integer.parseInt(sliderText);
        SizeSlider.setValue(x);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please insert Valid Number Only");
            SizeSliderTextField.setText("");
        }
    }//GEN-LAST:event_SizeSliderTextFieldActionPerformed

    private void SizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SizeSliderStateChanged
        String x = Integer.toString((SizeSlider.getValue()));
        SizeSliderTextField.setText(x);
    }//GEN-LAST:event_SizeSliderStateChanged

    private void SizeSliderTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SizeSliderTextFieldKeyTyped
                // TODO add your handling code here:
    }//GEN-LAST:event_SizeSliderTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ColorComboBox;
    private javax.swing.JComboBox<String> LifeCycleComboBox;
    private javax.swing.JComboBox<String> PerfumeComboBox;
    private javax.swing.JComboBox<String> RootComboBox;
    private javax.swing.JComboBox<String> SeasonComboBox;
    private javax.swing.JSlider SizeSlider;
    private javax.swing.JTextField SizeSliderTextField;
    private javax.swing.JComboBox<String> SoilComboBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton showFactsButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
