/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.clipsrules.jni.*;

/**
 *
 * @author Mostafa
 */
public class JFrameInterface extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInterface
     */
    
    Environment clips;
            
    public JFrameInterface() {
        clips = new Environment();
        clips.load("flower.clp");
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Clips Flowers Expert System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        StartJButton = new javax.swing.JButton();
        HowJButton = new javax.swing.JButton();
        SizeSlider = new javax.swing.JSlider();
        ColorComboBox = new javax.swing.JComboBox<>();
        SeasonComboBox = new javax.swing.JComboBox<>();
        LifeCycleComboBox = new javax.swing.JComboBox<>();
        RootComboBox = new javax.swing.JComboBox<>();
        SoilComboBox = new javax.swing.JComboBox<>();
        PerfumeComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SizeSliderTextField = new javax.swing.JTextField();
        FlowerNameJLabel = new javax.swing.JLabel();
        FlowerNameJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartJButton.setText("start");
        StartJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartJButtonActionPerformed(evt);
            }
        });

        HowJButton.setText("How?");
        HowJButton.setEnabled(false);
        HowJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowJButtonActionPerformed(evt);
            }
        });

        SizeSlider.setValue(10);
        SizeSlider.setMinimum(10);
        SizeSlider.setMaximum(300);
        SizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SizeSliderStateChanged(evt);
            }
        });

        ColorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Red", "Blue", "Yellow", "White", "Pink", "Purple", "Pinkish-Red" }));
        ColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorComboBoxActionPerformed(evt);
            }
        });

        SeasonComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Summer", "Spring", "Autumn", "Winter" }));

        LifeCycleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "One", "Many" }));
        LifeCycleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LifeCycleComboBoxActionPerformed(evt);
            }
        });

        RootComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Bulb", "Root" }));

        SoilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Acidic", "Loose", "Fertile", "Rich", "Well-Drained" }));
        SoilComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoilComboBoxActionPerformed(evt);
            }
        });

        PerfumeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "True", "False" }));
        PerfumeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfumeComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Size");

        jLabel2.setText("Life Cycle");

        jLabel3.setText("Color");

        jLabel4.setText("Season");

        jLabel5.setText("Root");

        jLabel6.setText("Soil");

        jLabel7.setText("Perfume");

        SizeSliderTextField.setText("10");
        SizeSliderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeSliderTextFieldActionPerformed(evt);
            }
        });
        SizeSliderTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SizeSliderTextFieldKeyTyped(evt);
            }
        });

        FlowerNameJLabel.setText("Flower's Name:");

        FlowerNameJTextField.setEditable(false);
        FlowerNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlowerNameJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PerfumeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(SizeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SizeSliderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RootComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SeasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LifeCycleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(FlowerNameJLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FlowerNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HowJButton))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ColorComboBox, LifeCycleComboBox, PerfumeComboBox, RootComboBox, SeasonComboBox, SoilComboBox});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SizeSliderTextField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SizeSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LifeCycleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(FlowerNameJLabel)
                    .addComponent(FlowerNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RootComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(HowJButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SoilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerfumeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(StartJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ColorComboBox, LifeCycleComboBox, PerfumeComboBox, RootComboBox, SeasonComboBox, SoilComboBox});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartJButtonActionPerformed
            // TODO add your handling code here:
            clips.reset();
            
            String Size = Integer.toString(SizeSlider.getValue());
            clips.eval("(assert (Size (PlantSize " + Size + ")))");
            
            String LifeCycle = LifeCycleComboBox.getSelectedItem().toString().toLowerCase();
            if(LifeCycle.length()>2)
                clips.eval("(assert (LifeCycle (PLifeCycle " + LifeCycle + ")))");
                
            String Color = ColorComboBox.getSelectedItem().toString().toLowerCase();
            if(Color.length()>2)
                clips.eval("(assert (Color (PlantColor " + Color + ")))");
            
            String Season = SeasonComboBox.getSelectedItem().toString().toLowerCase();
            if(Season.length()>2)
                clips.eval("(assert (Season (PlantSeason " + Season + ")))");
            
            String Root = RootComboBox.getSelectedItem().toString().toLowerCase();
            if(Root.length()>2)
                clips.eval("(assert (Root (PlantRoot " + Root + ")))");
            
            String Soil = SoilComboBox.getSelectedItem().toString().toLowerCase();
            if(Soil.length()>2)
                clips.eval("(assert (Soil (PlantSoil " + Soil + ")))");
            
            String Perfume = PerfumeComboBox.getSelectedItem().toString().toLowerCase();
            if(Perfume.length()>2)
                clips.eval("(assert (Perfume (PlantPerfume " + Perfume + ")))");
            
            clips.run();
            
            try {
                MultifieldValue mv = (MultifieldValue) (clips.eval("(find-all-facts ((?f Name)) TRUE)")); 
                FactAddressValue fv = (FactAddressValue) mv.get(mv.size()-1);
                String FlowersName = fv.getFactSlot("PlantName").toString();
                FlowerNameJTextField.setText(FlowersName);
                HowJButton.setEnabled(true);
            } catch (Exception ex) {
                FlowerNameJTextField.setText("None!");
            }
            
    }//GEN-LAST:event_StartJButtonActionPerformed

    private void HowJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowJButtonActionPerformed
        String[] fullMessage = new String[11];
        int n = 0;
        //Size and Height
        try {
            MultifieldValue mv1 = (MultifieldValue) (clips.eval("(find-fact ((?f Height)) TRUE)")); 
            FactAddressValue fv1 = (FactAddressValue) mv1.get(0);
            String FlowerHeight = fv1.getFactSlot("PlantHeight").toString(); 
            
            MultifieldValue mv2 = (MultifieldValue) (clips.eval("(find-fact ((?f Size)) TRUE)")); 
            FactAddressValue fv2 = (FactAddressValue) mv2.get(0);
            String FlowerSize = fv2.getFactSlot("PlantSize").toString();
            
            fullMessage[n++] = "The Size of the Flower is " + FlowerSize;
            fullMessage[n++] = "So The Height of the Flower is " + FlowerHeight;
        } catch (Exception ex) {
          clips.eval("(facts)");  
          System.out.println(fullMessage);
        }
        
        //Life Cycle and Life Type
        try {
            MultifieldValue mv3 = (MultifieldValue) (clips.eval("(find-fact ((?f LifeType)) TRUE)")); 
            FactAddressValue fv3 = (FactAddressValue) mv3.get(0);
            String FlowerLType = fv3.getFactSlot("PLifeType").toString(); 
            
            MultifieldValue mv4 = (MultifieldValue) (clips.eval("(find-fact ((?f LifeCycle)) TRUE)")); 
            FactAddressValue fv4 = (FactAddressValue) mv4.get(0);
            String FlowerLCycle = fv4.getFactSlot("PLifeCycle").toString();
            
            fullMessage[n++] = "The Life Cycle of the Flower is " + FlowerLCycle + " year(s)";
            fullMessage[n++] = "So the Life Type of the Flower is " + FlowerLType;
        } catch (Exception ex) {}
        
        //Color
        try {
            MultifieldValue mv5 = (MultifieldValue) (clips.eval("(find-fact ((?f Color)) TRUE)")); 
            FactAddressValue fv5 = (FactAddressValue) mv5.get(0);
            String FlowerColor = fv5.getFactSlot("PlantColor").toString();
            
            fullMessage[n++] = "The Flower's Color is " + FlowerColor;
        } catch (Exception ex) {}
        
        //Season
        try {
            MultifieldValue mv6 = (MultifieldValue) (clips.eval("(find-fact ((?f Season)) TRUE)")); 
            FactAddressValue fv6 = (FactAddressValue) mv6.get(0);
            String FlowerSeason = fv6.getFactSlot("PlantSeason").toString();
            
            fullMessage[n++] = "The Flower's Season is " + FlowerSeason;
        } catch (Exception ex) {}
        
        //Root
        try {
            MultifieldValue mv7 = (MultifieldValue) (clips.eval("(find-fact ((?f Root)) TRUE)")); 
            FactAddressValue fv7 = (FactAddressValue) mv7.get(0);
            String FlowerRoot = fv7.getFactSlot("PlantRoot").toString();
            
            fullMessage[n++] = "The Root Type of the Flower is " + FlowerRoot;
        } catch (Exception ex) {}
        
        //Soil
        try {
            MultifieldValue mv8 = (MultifieldValue) (clips.eval("(find-fact ((?f Soil)) TRUE)")); 
            FactAddressValue fv8 = (FactAddressValue) mv8.get(0);
            String FlowerSoil = fv8.getFactSlot("PlantSoil").toString();
            
            fullMessage[n++] = "The Soil Type of the Flower is " + FlowerSoil;
        } catch (Exception ex) {}
        
        //Perfumed
        try {
            MultifieldValue mv9 = (MultifieldValue) (clips.eval("(find-fact ((?f Perfume)) TRUE)")); 
            FactAddressValue fv9 = (FactAddressValue) mv9.get(0);
            String isPerfumed = fv9.getFactSlot("PlantPerfume").toString();
            
            if(isPerfumed.equals("true"))
                fullMessage[n++] = "The Flower is perfumed";
            else if(isPerfumed.equals("false"))
                fullMessage[n++] = "The Flower isn't perfumed";
        } catch (Exception ex) {}
        
        //Flower Name
        try {
                MultifieldValue mv10 = (MultifieldValue) (clips.eval("(find-all-facts ((?f Name)) TRUE)")); 
                FactAddressValue fv10 = (FactAddressValue) mv10.get(mv10.size()-1);
                String FlowersName = fv10.getFactSlot("PlantName").toString();
                
                fullMessage[n++] = "Therefore The Flower's name is " + FlowersName;
            } catch (Exception ex) {}
        
        JOptionPane.showMessageDialog(this, fullMessage);
    }//GEN-LAST:event_HowJButtonActionPerformed

    private void ColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorComboBoxActionPerformed

    private void SizeSliderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeSliderTextFieldActionPerformed
        String sliderText = SizeSliderTextField.getText();
        try {
        Integer.parseInt(sliderText);
        int x = Integer.parseInt(sliderText);
        clips.eval("(facts)");
        SizeSlider.setValue(x);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please insert Valid Number Only");
            SizeSliderTextField.setText("");
        }
        
    }//GEN-LAST:event_SizeSliderTextFieldActionPerformed

    private void SizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SizeSliderStateChanged
        String x = Integer.toString((SizeSlider.getValue()));
        SizeSliderTextField.setText(x);
    }//GEN-LAST:event_SizeSliderStateChanged

    private void SizeSliderTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SizeSliderTextFieldKeyTyped
                // TODO add your handling code here:
    }//GEN-LAST:event_SizeSliderTextFieldKeyTyped

    private void FlowerNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlowerNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlowerNameJTextFieldActionPerformed

    private void PerfumeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfumeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfumeComboBoxActionPerformed

    private void SoilComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoilComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoilComboBoxActionPerformed

    private void LifeCycleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LifeCycleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LifeCycleComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ColorComboBox;
    private javax.swing.JLabel FlowerNameJLabel;
    private javax.swing.JTextField FlowerNameJTextField;
    private javax.swing.JButton HowJButton;
    private javax.swing.JComboBox<String> LifeCycleComboBox;
    private javax.swing.JComboBox<String> PerfumeComboBox;
    private javax.swing.JComboBox<String> RootComboBox;
    private javax.swing.JComboBox<String> SeasonComboBox;
    private javax.swing.JSlider SizeSlider;
    private javax.swing.JTextField SizeSliderTextField;
    private javax.swing.JComboBox<String> SoilComboBox;
    private javax.swing.JButton StartJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
